# Generated by Django 4.2.4 on 2023-09-03 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mouse_alter_user_options_alter_product_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Производитель')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.AlterModelOptions(
            name='mouse',
            options={'verbose_name': 'Мышь', 'verbose_name_plural': 'Мыши'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='comments',
            name='advantages',
            field=models.TextField(blank=True, verbose_name='Преимущества'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='disadvantages',
            field=models.TextField(blank=True, verbose_name='Недостатки'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='case_color',
            field=models.CharField(choices=[('Beige', 'Бежевый'), ('White', 'Белый'), ('Turquoise', 'Бирюзовый'), ('Blue', 'Синий'), ('Yellow', 'Желтый'), ('Black', 'Черный')], default='Black', max_length=10, verbose_name='Цвет корпуса'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='sensor_type',
            field=models.CharField(choices=[('Laser', 'Лазерный'), ('Optical LED', 'Оптический светодиодный')], default='Laser', max_length=20, verbose_name='Тип сенсора'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='size',
            field=models.CharField(choices=[('Big', 'Большой'), ('Middle', 'Средний'), ('Small', 'Маленький')], default='Middle', max_length=10, verbose_name='Размер мыши'),
        ),
        migrations.AddField(
            model_name='mouse',
            name='manufacturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.manufacturer', verbose_name='Производитель'),
            preserve_default=False,
        ),
    ]
