# Generated by Django 4.2.4 on 2023-09-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_manufacturer_alter_mouse_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
    ]
